### PR TITLE
Refactor SPELL_MISSED

### PR DESCRIPTION
**Pull request by oscarwika**
I saw you've started the refactoring job, here is the work I've done on SPELL_MISSED so far.

It can probably be optimized even more or made more readable.

### CODE REVIEW

**Comment by oscarwika** [comment]
@jobackman It doesn't seem like I can add reviewers or anything, but I hope you see this at some point :D

**Comment by jobackman** [comment]
Awesome! 😄 I think I'll go ahead with https://github.com/jobackman/SpellNotifications/pull/5 first and then get to this one! 
If you're interested feel free to look over some minor changes I made to your refactoring in #5 

I need to continue my dayjob now but sometime tonight I think ill go ahead with that one. I've so far tested kicks, steals, purges, immunes, pets ad groundings on Retail. Tested kicks immunes/evades and pet deaths on BCC, but im much more limited there on what I can test since I have no shaman 😋

**Comment by oscarwika** [comment]
> Awesome! 😄 I think I'll go ahead with #5 first and then get to this one!
> If you're interested feel free to look over some minor changes I made to your refactoring in #5
> 
> I need to continue my dayjob now but sometime tonight I think ill go ahead with that one. I've so far tested kicks, steals, purges, immunes, pets ad groundings on Retail. Tested kicks immunes/evades and pet deaths on BCC, but im much more limited there on what I can test since I have no shaman 😋

This is a PR to the branch your currently working on btw #5, if you didn't notice. 😄 
I added "DEFLECT" to MissTypes on your PR and adjusted this PR so that it can be merged with your code before you take it into the main branch, if you want to!

Great that you have tested those things, I don't have a shaman on BCC either, but maybe I can ask a friend to test it or something. 😄

**Comment by jobackman** [comment]
> This is a PR to the branch your currently working on btw #5, if you didn't notice. 😄

Aaah, sweet! I did not notice that ^^ 

In that case feel free to merge it to the larger refactor PR 👍

**Review by jobackman — APPROVED** [review]

**Comment by oscarwika** [comment]
> > This is a PR to the branch your currently working on btw #5, if you didn't notice. 😄
> 
> Aaah, sweet! I did not notice that ^^
> 
> In that case feel free to merge it to the larger refactor PR 👍

Awesome 👍🏼

**Pull request merged**
